--osobaspraw
insert all
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(1,	'Adam',	'Pope',	'Przemoc',	1,	1)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(2,	'Ada',	'Wozniak',	'Wulgarny Jezyk',	2,	1)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(3,	'Mat',	'Kowal',	'Uzywki',	3,	1)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(4,	'Mateusz', 'Morawiecki',	'Dyskryminacja',	4,	1)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(5,	'Zbigniew',	'Chlebowski',	'Hazard',	5,	1)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(6,	'Matthew',	'Exe',	'Przemoc',	1,	2)
\into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(7,	'Gerwazy'	'Wozignoj',	'Wulgarny Jezyk',	2,	2)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(8,	'Marta',	'Paluch',	'Uzywki',	3,	2)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(9,	'Wojciech',	'Alszer',	'Dyskryminacja',	4,	2)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(10,	'Piort',	'Luszcz',	'Hazard',	5,	2)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(11,	'Jaroslaw',	'Kaminski',	'Przemoc',	1,	3)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(12,	'Mac',	'Mac',	'Wulgarny Jezyk',	2,	3)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(13,	'Elzbieta',	'Fuks',	'Uzywki',	3,	3)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(14,	'Sebastian',	'Salbert',	'Dyskryminacja',	4,	3)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(15,	'James',	'Allison', 'Hazard',	5,	3)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(16,	'Jean',	'Todt',	'Przemoc',	1,	4)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(17,	'Ross',	'Brawn',	'Wulgarny Jezyk',	2,	4)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(18,	'Katarzyna',	'Piasecka',	'Uzywki',	3,	4)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(19,	'Abelart',	'Giza',	'Dyskryminacja',	4,	4)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(20,	'Valteri',	'James',	'Hazard',	5,	4)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(21,	'Kacper',	'Rucinski',	'Przemoc',	1,	5)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(22,	'Toto',	'Wolff',	'Wulgarny Jezyk',	2,	5)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(23,	'Emily',	'Feld',	'Uzywki',	3,	5)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(24,	'Lukasz', 'Fabianski',	'Dyskryminacja',	4,	5)
into osoba spraw(idosoby, imie, nazwisko,kategoriasprawdzenia,kategoria_id_kategoria,zespolsprawdzajacy_idzespolu)
values(25,	'Carlin',	'Guy',	'Hazard',	5,	5);




--kategoria
insert all
into kategoria (id_kategoria, kategoria)
values(1,	'PRZEMOC')
into kategoria (id_kategoria, kategoria)
values(2,	'WULGARNY JEZYK')
into kategoria (id_kategoria, kategoria)
values(3,	'UZYWKI')
into kategoria (id_kategoria, kategoria)
values(4,	'DYSKRYMINACJA')
into kategoria (id_kategoria, kategoria)
values(5,	'HAZARD');


--sprawdzenie
insert all
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(1,	1)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(1,	2)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(1,	3)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(1,	4)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(1,	5)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(2,	6)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(2,	7)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(2,	8)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(2,	9)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(2,       10)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(3,	11)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(3,	12)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(3,	13)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(3,	14)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(3,	15)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(4,	16)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(4,	17)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(4,	18)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(4,	19)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(4,	20)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(5,	1)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(5,	2)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(5,	3)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(5,	4)
into sprawdzenie (gra_idgry, osobaspraw_idosoby)
values(5,	5);

--raport
insert all
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(1,	1,	1)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(2,	1,	2)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(3,	1,	3)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(4,	1,	4)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(5,	1,	5)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(6,	2,	6)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(7,	2,	7)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(8,	2,	8)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(9,	2,	9)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(10,	2,	10)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(11,	3,	11)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(12,	3,	13)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(13,	3,	13)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(14,	3,	14)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(15,	3,	15)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(16,	4,	16)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(17,	4,	17)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(18,	4,	18)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(19,	4,	19)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(20,	4,	19)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(21,	5,	1)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(22,	5,	2)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(24,	5,	3)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(25,	5,	4)
into raport (idraportu, sprawdzenie_gra_idgry, sprawdzenia_osoba_idosoby)
values(23,	5,	5);



--zespolsprawdzajacy
insert all
into zespolsprawdzajacy(idzespolu, nazwazespolu)
values(1,	'Zespol 1')
into zespolsprawdzajacy(idzespolu, nazwazespolu)
values(2,	'Zespol 2')
into zespolsprawdzajacy(idzespolu, nazwazespolu)
values(3,	'Zespol 3')
into zespolsprawdzajacy(idzespolu, nazwazespolu)
values(4,	'Zespol 4')
into zespolsprawdzajacy(idzespolu, nazwazespolu)
values(5,	'Zespol 5')
into zespolsprawdzajacy(idzespolu, nazwazespolu)
values(6,	'Zespol 6');

--werdykt
insert all
into werdykt(idwerdykty, gra_idgry,zespolsprawdzajacy_idzespolu)
values(1,	1,	1)
into werdykt(idwerdykty, gra_idgry,zespolsprawdzajacy_idzespolu)
values(2,	2,	2)
into werdykt(idwerdykty, gra_idgry,zespolsprawdzajacy_idzespolu)
values(3,	3,	3)
into werdykt(idwerdykty, gra_idgry,zespolsprawdzajacy_idzespolu)
values(4,	4,	4)
into werdykt(idwerdykty, gra_idgry,zespolsprawdzajacy_idzespolu)
values(5,	5,	1);

--gra
insert all
into gra(idgry, tytul)
values(1,	'Battlefield: 4')
into gra(idgry, tytul)
values(2,	'Battlefield: V')
into gra(idgry, tytul)
values(3,	'PUBG')
into gra(idgry, tytul)
values(4,	'Grand Theft Auto: V')
into gra(idgry, tytul)
values(5,	'Call of Duty: Black Ops IIII');

--granaplatforme
insert all
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(1,	1,	2)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(1,	2,	2)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(1,	3,	3)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(1,	4,	1)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(1,	5,	4)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(2,	1,	2)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(2,	5,	4)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(3,	1,	2)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(3,	5,	4)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(4,	4,	5)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
valies(4,	5,	6)
into grananaplatforme (platforma_idplatformy,gra_idgry,developer_iddev)
values(5,	1,	2);

--platforma
inset all
int platforma(idplatformy, nazwa)
values(1,	'PC')
int platforma(idplatformy, nazwa)
values(2,	'PS4')
int platforma(idplatformy, nazwa)
values(3,	'XONE')
int platforma(idplatformy, nazwa)
values(4,	'SWITCH')
int platforma(idplatformy, nazwa)
values(5,	'WIIU');

--developer
insert all
into developer (iddev, nazwa)
values(5,	'Rockstar North')
into developer (iddev, nazwa)
values(6,	'Sledgehammer Games')
into developer (iddev, nazwa)
values(1,	'Rockstar Games')
into developer (iddev, nazwa)
values(2,	'DICE')
into developer (iddev, nazwa)
values(3,	'PUBG CORP.')
into developer (iddev, nazwa)
values(4,	'Treyarch');